### ISSUE TITLE
Not accessing ha-card element with Sensor Card

### ISSUE THREAD

**Issue by zsarnett** [thomasloven/lovelace-card-modder#1]
HA-Version: 0.80.0b3
Hassio Build
Chrome Browser

Lovelace YAML:
```yaml
- type: custom:card-modder
  card:
      type: sensor
      entity: sensor.zack_home
      graph: false
  style:
      "margin": "10px"
      "border-radius": "25px"
      "box-shadow": "0 2px 4px rgba(0,0,0,0.18)"
```

HTML Rendered
![Example of HTML](https://i.gyazo.com/ea93cafd9a487d2f17361cdf4214952b.png)
