### ISSUE TITLE
Thermostat 

### ISSUE THREAD

**Issue by hwikene** [thomasloven/lovelace-card-modder#13]
Hi.
After i updated to 0.85 on Docker, thermostat card dont work with "card-modder" 
If i remove "card-modder" everything works ok. 
Here is my code: 

```
      - id: 413a234a906b4af198444c497a1f562a  # Automatically created id
        type: vertical-stack
        cards:
          - type: custom:card-modder
            card:
              type: thermostat
              entity: climate.vetle
              name: Vetle
            style:
              border-radius: 20px
              border: solid 1px rgba(100,100,100,0.3)
              box-shadow: 3px 3px rgba(0,0,0,0.4)
              overflow: hidden
```
This is how it looks in frontend. 
![2019-01-11_08h13_46](https://user-images.githubusercontent.com/17985923/51018706-dc6e8480-1578-11e9-9120-4497b3694b2d.jpg)
