### ISSUE TITLE
[SOLVED] Error after updating to latest version

### ISSUE THREAD

**Issue by woody4165** [thomasloven/lovelace-card-modder#17]
Hi Thomas

I've just updated to latest version of card-modder and now I'm getting an error.

![schermata 2019-01-16 alle 16 44 26](https://user-images.githubusercontent.com/6501444/51260190-0b885a00-19ae-11e9-82f6-5655c60abdb2.png)

This is my config

```
          - type: custom:card-modder
            style:
              background-repeat: no-repeat
              background-color: rgba(246,244,191,1)
              background-size: 100% 400px
              border-radius: 20px
              border: solid 1px rgba(100,100,100,0.3)
            card:
              type: custom:dark-sky-weather-card
              entity_sun: sun.sun
              entity_sunup: sensor.nextsunrise
              entity_sundown: sensor.nextsunset
              entity_daily_summary: sensor.dark_sky_daily_summary
              entity_today_summary: sensor.dark_sky_hourly_summary
              entity_current_conditions: sensor.dark_sky_icon
              entity_humidity: sensor.dark_sky_humidity
              entity_pressure: sensor.dark_sky_pressure
              entity_temperature: sensor.dark_sky_temperature
              entity_feelstemp: sensor.dark_sky_apparent_temperature
              entity_visibility: sensor.dark_sky_visibility
              entity_wind_bearing: sensor.dark_sky_wind_bearing
              entity_wind_speed: sensor.dark_sky_wind_speed
              entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
              entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
              entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
              entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
              entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
              entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_1
              entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_2
              entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_3
              entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_4
              entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_5
              entity_forecast_pop_1: sensor.dark_sky_precip_probability_1
              entity_forecast_pop_2: sensor.dark_sky_precip_probability_2
              entity_forecast_pop_3: sensor.dark_sky_precip_probability_3
              entity_forecast_pop_4: sensor.dark_sky_precip_probability_4
              entity_forecast_pop_5: sensor.dark_sky_precip_probability_5
              entity_forecast_icon_1: sensor.dark_sky_icon_1
              entity_forecast_icon_2: sensor.dark_sky_icon_2
              entity_forecast_icon_3: sensor.dark_sky_icon_3
              entity_forecast_icon_4: sensor.dark_sky_icon_4
              entity_forecast_icon_5: sensor.dark_sky_icon_5
              entity_forecast_sum_1: sensor.dark_sky_summary_1
              entity_forecast_sum_2: sensor.dark_sky_summary_2
              entity_forecast_sum_3: sensor.dark_sky_summary_3
              entity_forecast_sum_4: sensor.dark_sky_summary_4
              entity_forecast_sum_5: sensor.dark_sky_summary_5

```

Prior of updating all was working fine, then I  just cut the text from the <code> page and copied in the file locally.

What can I check?

Thanks
