### ISSUE TITLE
border-radius not working on glance cards anymore.

### ISSUE THREAD

**Issue by Sjeff** [thomasloven/lovelace-card-modder#2]
HA-version: 0.80.1
Docker 
Chrome/Safari

Yaml:
```
          - type: custom:card-modder
            card:  
              type: glance
              title: Intel NUC
              column_width: calc(100% / 5)
              entities:
                - sensor.sonoffpow02_current
                - sensor.sonoffpow02_power
                - sensor.sonoffpow02_voltage
                - entity: sensor.sonoffpow02_today
                  name: Vandaag
                - entity: sensor.sonoffpow02_yesterday
                  name: Gister
            style:
              "--paper-card-background-color": "#2b2d3199"
              "border-radius": "20px"
              "color": "white"
```
![example](https://user-images.githubusercontent.com/11430228/46969145-68c1f600-d0b5-11e8-8318-e823cbbfeca8.JPG)
