### ISSUE TITLE
Modding an entity-filter card causes header to lose style

### ISSUE THREAD

**Issue by chipriley** [thomasloven/lovelace-card-modder#20]
Adding a modification to an entity-filter card, at least in my setup, is causing the header element to lose style.  Inspecting the element shows that `<style>` of the `<div>` is dropping the `@apply --paper-font-headline` and, therefore, showing the header text as regular text.  Here's my yaml:

```
- type: custom:card-modder
        style:
          border-radius: 10px
        card:
          type: entity-filter
          card:
            show_header_toggle: false
            title: Stuff Turned On/Running
          entities:
            ...
```
The inspector is saying that `@apply --paper-font-headline` is an "Unknown property name".  However, for other cards modded with the same style, it's working (such as on a glance card).  Am I doing something wrong? 
![image](https://user-images.githubusercontent.com/168062/51564312-8640f180-1e54-11e9-892e-83544ee22746.png)
EDIT:  Using Chrome Version 72.0.3626.64 (Official Build) beta (64-bit) on macOS.
