### ISSUE TITLE
Weird issue when modding map card inside a vertical stack

### ISSUE THREAD

**Issue by lizaoreo** [thomasloven/lovelace-card-modder#21]
When I have a card-modder modding a map card in a vertical-stack card, it loads fine, and is modded.  But when I switch "tabs" and switch back, it throws some errors and the map becomes blank.  It stays this way until I refresh the page.  I've tried clearing cache with no luck.  If I don't put the map card in a vertical stack it loads fine, no issues changing tabs.  This was all in Chrome.  I also tried in Firefox, which oddly does not cause a Home Assistant error, but when changing tabs, the map card just disappears completely.  The errors are below along with the map after it errors.

Code I'm using is here:
```yaml
          - type: vertical-stack
            cards:          
              - type: custom:card-modder
                style:
                  --primary-text-color: black
                card:
                  type: map
                  entities:
                    - device_tracker.michael_michael
                    - device_tracker.christy_christy
                    - zone.home
                  aspect_ratio: 50%
                  default_zoom: 16
```

![image](https://user-images.githubusercontent.com/19540692/51810995-f1396080-2278-11e9-8f16-b9bb7b978012.png)
![image](https://user-images.githubusercontent.com/19540692/51811014-06ae8a80-2279-11e9-9f94-29a035f059a8.png)
