### ISSUE TITLE
Rounding corners doesnt work with picture-elements card

### ISSUE THREAD

**Issue by Tontze** [thomasloven/lovelace-card-modder#22]
This is what happens : 

![huomautus 2019-02-02 231254](https://user-images.githubusercontent.com/28216916/52169413-986a3c00-2740-11e9-9fd5-ace78dccad66.jpg)

Works fine with picture-entity

```
      - type: custom:card-modder
        style:
           border-radius: 30px
           border: solid 1px rgba(100,100,100,0.3)
           color: "#999999"
           box-shadow: 3px 3px rgba(0,0,0,0.4)
        card:
          type: picture-elements
          image: /local/terassi.jpeg
          elements:
            - type: state-icon
              tap_action:
                action: toggle
              entity: light.henna
              style:
                top: 47%
                left: 42%
```
