### ISSUE TITLE
calendar card

### ISSUE THREAD

**Issue by kugan49** [thomasloven/lovelace-card-modder#27]
I have an issue with this card :
[calendar-card](https://github.com/ljmerza/calendar-card/blob/master/calendar-card.js)

Style is applied on first div :
```html
<calendar-card style="background-image: url(&quot;/local/background/cardback.png&quot;); background-repeat: no-repeat; background-color: rgba(50, 50, 50, 0.3); background-size: 100% 100%; border-radius: 20px; border: 1px solid rgba(100, 100, 100, 0.3); box-shadow: rgba(0, 0, 0, 0.4) 3px 3px; overflow: hidden;"></calendar-card>

```

But for working style this should be applied on :

```html
<ha-card class="calendar-card">
      </ha-card>
```

which is just under.

my lovelace config :

```yaml

 - type: custom:card-modder                                                                                                                                                                                       
    card:                                                                                                                                                                                                          
      type: custom:calendar-card                                                                                                                                                                                   
      title: "Planning ramassage ordure"                                                                                                                                                                           
      numberOfDays: 14                                                                                                                                                                                             
      showColors: true                                                                                                                                                                                             
      entities:                                                                                                                                                                                                    
        - calendar.trash                                                                                                                                                                                           
        - calendar.test_raspberry_informatique                                                                                                                                                                     
    style:                                                                                                                                                                                                         
      background-image: url("/local/background/cardback.png")                                                                                                                                                      
      background-repeat: no-repeat                                                                                                                                                                                 
      background-color: rgba(50,50,50,0.3)                                                                                                                                                                         
      background-size: 100% 100%                                                                                                                                                                                   
      border-radius: 20px                                                                                                                                                                                          
      border: solid 1px rgba(100,100,100,0.3)                                                                                                                                                                      
      box-shadow: 3px 3px rgba(0,0,0,0.4)                                                                                                                                                                          
      overflow: hidden                            
```
