### ISSUE TITLE
modder inside picture-elements

### ISSUE THREAD

**Issue by Hooorny** [thomasloven/lovelace-card-modder#29]
It seems that card-modder do not fully work for custom cards inside picture-elements.
I want to disable the box-shadow for a custom card inside picture-elements card, but the shadow style is inherited from :host ...

```yaml
      - type: picture-elements
        image: /local/3x1-00000000.png
        elements:
          - type: custom:card-modder
            style:
              box-shadow: none
              transform: translate(-50%)
              top: 0
              left: 50%
            card:
              type: custom:dual-gauge-card
```
![bildschirmfoto von 2019-03-03 11-15-43](https://user-images.githubusercontent.com/1502201/53693817-dbeab100-3da5-11e9-81ca-d1778b2c88e2.png)
