### ISSUE TITLE
Column_width for glance card is not used

### ISSUE THREAD

**Issue by gerard33** [thomasloven/lovelace-card-modder#3]
When setting `column_width` for a glance card this value is not being used.
In the example below there should be 6 entities in a row, but the card-modder will only show 5 and the 6th will be shown on a second row.

This has changed in the latest version.

```yaml
- type: custom:swipe-card
  parameters:
  cards:
      - type: custom:card-modder
      card:
          type: glance
          show_name: false
          column_width: calc(100% / 6)
          entities:
          - device_tracker.1
          - device_tracker.2
          - device_tracker.3
          - binary_sensor.1
          - sensor.1
          - sensor.temperature_2
      style:
          background-color: rgba(52, 73, 94, 0.1)
```
