### ISSUE TITLE
More-info not working

### ISSUE THREAD

**Issue by arsaboo** [thomasloven/lovelace-card-modder#31]
@iantrich and I debugged [this issue](https://github.com/custom-cards/config-template-card/issues/7) about `more-info` not working and realized that the issue is with `card-modder`. You can replicate the same using the following config:
```yaml
      - type: 'custom:hui-entities-card'
        title: Test Modder
        show_header_toggle: false
        entities:
          - type: 'custom:card-modder'
            style:
              '--paper-item-icon-color': 'rgb(194, 39, 45)'
            card:
              type: 'custom:hui-sensor-entity-row'
              entity: sensor.outside_humidity
              icon: 'mdi:arrow-up-bold-circle'
```
When you click on the entity, `more-info` does not show up.

**Comment by iantrich** [comment]
I haven't started debugging this on the card-modder side, but my initial observations is that some of the inherited styles are not being properly received. If it helps, here's my test view I created to start debugging this using the demo sensor platform
```yaml
  - cards:
      - config:
          entities:
            - card:
                entity: sensor.outside_humidity
                icon: >-
                  ${parseFloat(states['sensor.outside_humidity'].state) > 0 ?
                  'mdi:arrow-up-bold-circle' : 'mdi:arrow-down-bold-circle' }
                type: 'custom:hui-sensor-entity-row'
              style:
                '--paper-item-icon-color': >-
                  ${var state =
                  parseFloat(states['sensor.outside_humidity'].state); state <=
                  0 ? 'rgb(194, 39, 45)' : 'rgb(37, 145, 60)'}
              type: 'custom:card-modder'
          show_header_toggle: false
          title: Test Template/Modder
          type: 'custom:hui-entities-card'
        entities:
          - sensor.outside_humidity
        type: 'custom:config-template-card'
      - config:
          entities:
            - entity: sensor.outside_humidity
              icon: >-
                ${parseFloat(states['sensor.outside_humidity'].state) > 0 ?
                'mdi:arrow-up-bold-circle' : 'mdi:arrow-down-bold-circle' }
              type: 'custom:hui-sensor-entity-row'
          show_header_toggle: false
          title: Test Template
          type: 'custom:hui-entities-card'
        entities:
          - sensor.outside_humidity
        type: 'custom:config-template-card'
      - entities:
          - card:
              entity: sensor.outside_humidity
              icon: 'mdi:arrow-up-bold-circle'
              type: 'custom:hui-sensor-entity-row'
            style:
              '--paper-item-icon-color': red
            type: 'custom:card-modder'
        show_header_toggle: false
        title: Test Modder
        type: 'custom:hui-entities-card'
      - entities:
          - sensor.outside_humidity
        show_header_toggle: false
        title: Test Core
        type: 'custom:hui-entities-card'
    title: Test More-Info
```

**Comment by thomasloven** [comment]
This is due to how the entities card handles clicks. When a row is clicked it will open the more info dialog for the `entity:` of that row - if it exists.

Adding an `entity:` entry to the card-modder works:
```yaml
      - type: 'custom:hui-entities-card'
        title: Test Modder
        show_header_toggle: false
        entities:
          - type: 'custom:card-modder'
            entity: sensor.outside_humidity
            style:
              '--paper-item-icon-color': 'rgb(194, 39, 45)'
            card:
              type: 'custom:hui-sensor-entity-row'
              entity: sensor.outside_humidity
              icon: 'mdi:arrow-up-bold-circle'
```
