### ISSUE TITLE
card-modder seems broken with entities on 0.93.0

### ISSUE THREAD

**Issue by RomRider** [thomasloven/lovelace-card-modder#37]
Hi, 

The last working version working for me was 0.92.2, in 0.93.0.
When the modded card is an entities card, there seem to be a new object between the `<ha-card>` and the content and the padding now seems to be applied on it:
`<div id="states" class="card-content">`

Not sure, if it was already there before.

Exemple config (it's embedded in a vertical-stack-in-card, if that can change something and wrapped with card-loader):
```yaml
- type: custom:card-modder
  # extra_styles: '#states { padding: 0px !important; }' also tried this but nothing happens
  style:
    padding: 0px
  card:
    type: entities
    entities:
      - type: custom:slider-entity-row
        entity: cover.living_room_covers
        full_row: true
        hide_state: true
```

Thanks for your help.
Cheers

**Comment by RomRider** [comment]
Seems to work with:
```yaml
              extra_styles: >
                .card-content {
                  padding: 0px
                }
```
