### ISSUE TITLE
Breaking Change to Certain Styles

### ISSUE THREAD

**Issue by apop880** [thomasloven/lovelace-card-modder#38]
Not sure whether this falls under an issue or if documentation just needs to be updated, but after upgrading from 0.92.2 to 0.93.2, part of my card-modder configuration broke.

Old config:
```yaml
- type: 'custom:card-modder'
  card:
    type: entities
    show_header_toggle: false
    entities:
      - type: 'custom:slider-entity-row'
        entity: media_player.receiver
        full_row: true
        hide_state: true
  style:
    '--paper-card-background-color': 'rgba(255,255,255,0.45)'
    border-radius: 10px
    padding: 0px 5px 0px 5px
    margin: 10px
````
Here is how it looked:
![image](https://user-images.githubusercontent.com/41379678/58975620-02e0c680-878b-11e9-85a6-910f53c87b8f.png)

After upgrading, the background and border-radius still looked good, but there were issues around the internal padding:
![image](https://user-images.githubusercontent.com/41379678/58975608-fa888b80-878a-11e9-8636-e280371048bf.png)

After playing with Chrome Dev Tools, it looks like there appears to be an extra container, `card-content`, that was adding 16px of padding internally. I had to add the following to `extra_styles` to fix this:
```yaml
  extra_styles: >
    .card-content {
      padding: 0px;
    }
```

Again, I think this change could be documented in the readme, or card-modder should be updated to zero out `card-content` padding if padding is applied using card-modder.
