### ISSUE TITLE
Glance Card disappears with Card Modder

### ISSUE THREAD

**Issue by Sjeff** [thomasloven/lovelace-card-modder#4]
HA-version: 0.80.3
Docker
Chrome/Safari

Sorry to bother you again.

When refreshing the page (f5) the card disappears and shows this error in chrome

<img width="650" alt="error" src="https://user-images.githubusercontent.com/11430228/47203411-968e8f80-d380-11e8-8c2d-964702e8146f.png">

When i remove the custom:card-modder the glance card wil return and no error is shown.

Yaml:
```
  - title: Info
    id: info
    icon: mdi:lan
    cards:
      - type: vertical-stack
        cards:
          - type: custom:card-modder
            card:  
              type: glance
              column_width: calc(100% / 4)
              entities:
                - sensor.system_hp_envy_5640
                - sensor.system_plugwise_p1
                - sensor.system_sonoffpow01
                - sensor.system_sonoffpow02
            style:
              "--paper-card-background-color": "#2b2d3199"
              "border-radius": "20px"
              "color": "white"
```

**Comment by Sjeff** [comment]
- cleared cache, recreated the glance card and disappeared again.
- reset chrome to "factory defaults", removed the app (ios), reinstalled the app, recreated the glance card and disappeared again.
- cleared cache, removed vertical-stack and custom:column-card, recreated the glance card and disappeared again.

removed custom:card-modder and the glance card will stay.

same behavior in Internet Explorer, Edge and Firefox.

i have no idea what is happening here.

**Comment by thomasloven** [comment]
Ok. I see what's happening. I'll see what I can do...

**Comment by thomasloven** [comment]
I think this should fix it, but now you need to import the card as a module:

```yaml
resources:
  - url: /local/card-modder.js
    type: module
```
