### ISSUE TITLE
Can't use upcoming_media custom card with card modder

### ISSUE THREAD

**Issue by gbdavidx** [thomasloven/lovelace-card-modder#5]
No errors, nothing displays
```

resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.2.2
    type: js
  - url: /local/custom_ui/ecobee-card.js
    type: js
  - url: /local/card-modder.js
    type: module

name: My Awesome Home
views:
  - id: 1
    Name: Home
    cards:
      type: vertical-stack
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:card-modder
              card:
                type: custom:upcoming-media-card
                elements:
                  - type: state-label
                    entity: sensor.sonarr_upcoming_media
              style:                 
              border-radius: 20px
              border: solid 1px rgba(100,100,100,0.3)
              color: "#999999"
              box-shadow: 3px 3px rgba(0,0,0,0.4)
```
