### ISSUE TITLE
Gauge Card disappears with Card Modder

### ISSUE THREAD

**Issue by JareckiB12** [thomasloven/lovelace-card-modder#6]
Gauge type card disappears with card modder. No errors in console.
If I import as js, the same problem occurs

ui-lovelace.yaml:

```
title: HAL 9000
#panel: true
resources:
  - url: /local/layout-card.js
    type: js
  - url: /local/card-modder.js
    type: module
views:
  - title: Dom
    id: dom
    icon: mdi:home
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:card-modder
            style:
              border-radius: 5px
            card:
              id: temperatura_zachod
              title: Zachód
              type: gauge
              min: -30
              max: 50
              severity:
                green: 15
                yellow: 25
                red: 35
              entity: sensor.temperature_158d0001d36d02
          - id: wilgotnosc_zachod
            title: Zachód
            type: gauge
            min: 0
            max: 100
            severity:
              green: 40
              yellow: 60
              red: 80
            entity: sensor.humidity_158d0001d36d02
```
